name: Self-hosted deb packages kernel (old)
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit or tag to build'
        required: true
        default: 'v6.12.43-wyref'
      arch:
        description: "Target architecture"
        required: true
        default: 'armv7'
        type: choice
        options:
          - armv7
      gcc:
        description: "GCC Version"
        required: true
        default: 'gcc7'
        type: choice
        options:
          - gcc6
          - gcc7
          - gcc8
          
jobs:
  build:
    name: Build kernel
    runs-on: self-hosted
    steps:
      - name: Checkout HEAD Kernel Source
        uses: actions/checkout@v4

      - name: Prepare repository
        run: git config --global --add safe.directory "$(pwd)"

      - name: Set up ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: ${{ runner.os }}-kernel-build-${{ inputs.arch }}-${{ inputs.gcc }}-${{ inputs.commit }}
          restore-keys: |
            ${{ runner.os }}-kernel-build-${{ inputs.arch }}-${{ inputs.gcc }}-${{ inputs.commit }}-
            ${{ runner.os }}-kernel-build-${{ inputs.arch }}-${{ inputs.gcc }}-

      - name: Build kernel inside aarch64 container
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: aarch64
          distro: ubuntu18.04
          githubToken: ${{ github.token }}
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --platform linux/arm64
            --volume "${PWD}/artifacts:/artifacts"
          install: |
            hostname ryzen5-7600-builder
            exec $SHELL
            dpkg --add-architecture armhf
            apt-get update
            DEBIAN_FRONTEND=noninteractive apt-get install -y \
              build-essential bc cpio kmod rsync libc6-dev perl gcc gcc-6 gcc-8 \
              gnupg libssl-dev libssl-dev:armhf libelf-dev lsb-release debhelper \
              patchutils lzop liblz4-tool ccache flex bison texinfo \
              gcc-arm-linux-gnueabihf gcc-6-arm-linux-gnueabihf gcc-8-arm-linux-gnueabihf
          run: |
            set -e
            export USE_CCACHE=1
            export CCACHE_DIR=${GITHUB_WORKSPACE}/.ccache
            export PATH="/usr/lib/ccache:$PATH"

            TAG="${{ inputs.commit }}"
            VERSION="${TAG#v}"
            VER="${VERSION%-*}"

            make LOCALVERSION= mrproper
            
            update-alternatives --install /usr/bin/arm-linux-gnueabihf-gcc arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-6 70
            update-alternatives --install /usr/bin/arm-linux-gnueabihf-gcc arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-7 80
            update-alternatives --install /usr/bin/arm-linux-gnueabihf-gcc arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-8 90
            #update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 70
            #update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 80
            #update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90
            
            if [ "${{ inputs.gcc }}" = "gcc6" ]; then
              update-alternatives --set arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-6
            elif [ "${{ inputs.gcc }}" = "gcc7" ]; then
              update-alternatives --set arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-7
            else
              update-alternatives --set arm-linux-gnueabihf-gcc /usr/bin/arm-linux-gnueabihf-gcc-8
            fi

            #if [ "${{ inputs.gcc }}" = "gcc6" ]; then
            #  update-alternatives --set gcc /usr/bin/gcc-6
            #elif [ "${{ inputs.gcc }}" = "gcc7" ]; then
            #  update-alternatives --set gcc /usr/bin/gcc-7
            #else
            #  update-alternatives --set gcc /usr/bin/gcc-8
            #fi
            
            echo 11 | tee scripts/package/debian/compat
            mkdir -p debian
            echo 11 | tee debian/compat
            
            make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- LOCALVERSION= uz801v3_defconfig
            DEB_BUILD_OPTIONS=compress=gzip KBUILD_DEBARCH=armhf make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- CC='ccache arm-linux-gnueabihf-gcc' LOCALVERSION="" \
            bindeb-pkg && rm -f ../*${{ steps.stripver.outputs.VER }}* && \
            DEB_BUILD_OPTIONS=compress=gzip KBUILD_DEBARCH=armhf make -j$(nproc) ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- CC='ccache arm-linux-gnueabihf-gcc' LOCALVERSION="" \
            bindeb-pkg

            #make LOCALVERSION= uz801v3_defconfig
            #DEB_BUILD_OPTIONS=compress=gzip make CC='ccache gcc' LOCALVERSION= \
            #-j$(nproc) bindeb-pkg && rm -f ../*${{ steps.stripver.outputs.VER }}* && \
            #DEB_BUILD_OPTIONS=compress=gzip make CC='ccache gcc' LOCALVERSION= \
            #-j$(nproc) bindeb-pkg
  
            find .. -maxdepth 1 -name "linux-*${VER}*.deb" -exec mv {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-debs
          path: artifacts/*
